package FinalProject;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class addBurgerItemsPanel extends javax.swing.JPanel {

    public addBurgerItemsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        burgerIng1Label = new javax.swing.JLabel();
        burgerIng2Label = new javax.swing.JLabel();
        burgerIng3Label = new javax.swing.JLabel();
        burgerIng4Label = new javax.swing.JLabel();
        sideLabel = new javax.swing.JLabel();
        drinkLabel = new javax.swing.JLabel();
        saveNewBurgerItemsButton = new javax.swing.JButton();
        burgerIng2TextField = new javax.swing.JTextField();
        burgerIng1TextField = new javax.swing.JTextField();
        burgerIng4TextField = new javax.swing.JTextField();
        burgerIng3TextField = new javax.swing.JTextField();
        sideTextField = new javax.swing.JTextField();
        drinkTextField = new javax.swing.JTextField();
        addBurgerItemsLabel = new javax.swing.JLabel();
        burgerPicLLabel = new javax.swing.JLabel();
        burgerPicRLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 0));
        setMaximumSize(new java.awt.Dimension(800, 370));
        setMinimumSize(new java.awt.Dimension(800, 370));
        setPreferredSize(new java.awt.Dimension(800, 370));

        burgerIng1Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng1Label.setText("Ingredient 1:");

        burgerIng2Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng2Label.setText("Ingredient 2:");

        burgerIng3Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng3Label.setText("Ingredient 3:");

        burgerIng4Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng4Label.setText("Ingredient 4:");

        sideLabel.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sideLabel.setText("Side:");

        drinkLabel.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        drinkLabel.setText("Drink:");

        saveNewBurgerItemsButton.setBackground(new java.awt.Color(204, 255, 255));
        saveNewBurgerItemsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveNewBurgerItemsButton.setText("Save New Items");
        saveNewBurgerItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveNewBurgerItemsButtonMouseClicked(evt);
            }
        });
        saveNewBurgerItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewBurgerItemsButtonActionPerformed(evt);
            }
        });

        addBurgerItemsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addBurgerItemsLabel.setText("Add Burger Items");

        burgerPicLLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/Real Sprites/BugerButton_C.png"))); // NOI18N

        burgerPicRLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/Real Sprites/BugerButton_C.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(burgerPicLLabel)
                        .addGap(35, 35, 35)
                        .addComponent(addBurgerItemsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(burgerIng1Label)
                                .addGap(30, 30, 30)
                                .addComponent(burgerIng1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(burgerIng3Label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(burgerIng4Label)
                                .addGap(30, 30, 30)
                                .addComponent(burgerIng4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(burgerIng2Label)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(burgerIng2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(burgerIng3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(burgerPicRLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drinkLabel)
                            .addComponent(sideLabel))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(saveNewBurgerItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(addBurgerItemsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(burgerPicRLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(burgerPicLLabel)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burgerIng1Label)
                    .addComponent(burgerIng1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(burgerIng2Label)
                            .addComponent(burgerIng2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(burgerIng3Label)
                            .addComponent(burgerIng3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sideLabel)
                            .addComponent(sideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(drinkLabel)
                            .addComponent(drinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(saveNewBurgerItemsButton)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burgerIng4Label)
                    .addComponent(burgerIng4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveNewBurgerItemsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveNewBurgerItemsButtonMouseClicked
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to add the new item(s)?", "Save Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        }
// <editor-fold>//saveIngredients             
        if (burgerIng1TextField.getText().isEmpty() == false) {
            FinalProject.bingredients1.add(burgerIng1TextField.getText());
            saveBIng1();
            burgerIng1TextField.setText("");
        }
        if (burgerIng2TextField.getText().isEmpty() == false) {
            FinalProject.bingredients2.add(burgerIng2TextField.getText());
            saveBIng2();
            burgerIng2TextField.setText("");
        }
        if (burgerIng3TextField.getText().isEmpty() == false) {
            FinalProject.bingredients3.add(burgerIng3TextField.getText());
            saveBIng3();
            burgerIng3TextField.setText("");
        }
        if (burgerIng4TextField.getText().isEmpty() == false) {
            FinalProject.bingredients4.add(burgerIng4TextField.getText());
            saveBIng4();
            burgerIng4TextField.setText("");
        }
        if (sideTextField.getText().isEmpty() == false) {
            FinalProject.sideOrder.add(sideTextField.getText());
            saveSide();
            sideTextField.setText("");
        }
        if (drinkTextField.getText().isEmpty() == false) {
            FinalProject.drinkOrder.add(drinkTextField.getText());
            saveDrink();
            drinkTextField.setText("");
        }
// </editor-fold>//ingredient arrays
    }//GEN-LAST:event_saveNewBurgerItemsButtonMouseClicked

    private void saveNewBurgerItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewBurgerItemsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveNewBurgerItemsButtonActionPerformed

    public static void saveBIng1() {
        try {
            FileWriter fb1 = new FileWriter("savedIngredients/bingredients1.txt");
            BufferedWriter bb1 = new BufferedWriter(fb1);
            for (int i = 0; i < FinalProject.bingredients1.size(); i++) {
                bb1.write(FinalProject.bingredients1.get(i) + "\n");
            }
            bb1.close();
        } catch (IOException e) {
            System.out.println("The save was unsuccessful.");
        }
    }

    public static void saveBIng2() {
        try {
            FileWriter fb2 = new FileWriter("savedIngredients/bingredients2.txt");
            BufferedWriter bb2 = new BufferedWriter(fb2);
            for (int i = 0; i < FinalProject.bingredients2.size(); i++) {
                bb2.write(FinalProject.bingredients2.get(i) + "\n");
            }
            bb2.close();
        } catch (IOException e) {
            System.out.println("The save was unsuccessful.");
        }
    }

    public static void saveBIng3() {
        try {
            FileWriter fb3 = new FileWriter("savedIngredients/bingredients3.txt");
            BufferedWriter bb3 = new BufferedWriter(fb3);
            for (int i = 0; i < FinalProject.bingredients3.size(); i++) {
                bb3.write(FinalProject.bingredients3.get(i) + "\n");
            }
            bb3.close();
        } catch (IOException e) {
            System.out.println("The save was unsuccessful.");
        }
    }

    public static void saveBIng4() {
        try {
            FileWriter fb4 = new FileWriter("savedIngredients/bingredients4.txt");
            BufferedWriter bb4 = new BufferedWriter(fb4);
            for (int i = 0; i < FinalProject.bingredients4.size(); i++) {
                bb4.write(FinalProject.bingredients4.get(i) + "\n");
            }
            bb4.close();
        } catch (IOException e) {
            System.out.println("The save was unsuccessful.");
        }
    }

    public static void saveSide() {
        try {
            FileWriter fside = new FileWriter("savedIngredients/sideOrder.txt");
            BufferedWriter bside = new BufferedWriter(fside);
            for (int i = 0; i < FinalProject.sideOrder.size(); i++) {
                bside.write(FinalProject.sideOrder.get(i) + "\n");
            }
            bside.close();
        } catch (IOException e) {
            System.out.println("The save was unsuccessful.");
        }
    }

    public static void saveDrink() {
        try {
            FileWriter fdrink = new FileWriter("savedIngredients/drinkOrder.txt");
            BufferedWriter bdrink = new BufferedWriter(fdrink);
            for (int i = 0; i < FinalProject.drinkOrder.size(); i++) {
                bdrink.write(FinalProject.drinkOrder.get(i) + "\n");
            }
            bdrink.close();
        } catch (IOException e) {
            System.out.println("The save was unsuccessful.");
        }
    }

    private JFrame frame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBurgerItemsLabel;
    private javax.swing.JLabel burgerIng1Label;
    private javax.swing.JTextField burgerIng1TextField;
    private javax.swing.JLabel burgerIng2Label;
    private javax.swing.JTextField burgerIng2TextField;
    private javax.swing.JLabel burgerIng3Label;
    private javax.swing.JTextField burgerIng3TextField;
    private javax.swing.JLabel burgerIng4Label;
    private javax.swing.JTextField burgerIng4TextField;
    private javax.swing.JLabel burgerPicLLabel;
    private javax.swing.JLabel burgerPicRLabel;
    private javax.swing.JLabel drinkLabel;
    private javax.swing.JTextField drinkTextField;
    private javax.swing.JButton saveNewBurgerItemsButton;
    private javax.swing.JLabel sideLabel;
    private javax.swing.JTextField sideTextField;
    // End of variables declaration//GEN-END:variables
}
