package FinalProject;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

public class adminEditingPanel extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();

    addBurgerItemsPanel pAddBurger;
    addHotdogItemsPanel pAddHotdog;
    addSandwichItemsPanel pAddSandwich;

    removeBurgerItemsPanel pRemoveBurger;
    removeHotdogItemsPanel pRemoveHotdog;
    removeSandwichItemsPanel pRemoveSandwich;
    
    orderHistoryPanel pOrderHistory;

    public adminEditingPanel() {
        initComponents();
        pAddBurger = new addBurgerItemsPanel();
        pAddHotdog = new addHotdogItemsPanel();
        pAddSandwich = new addSandwichItemsPanel();

        pRemoveBurger = new removeBurgerItemsPanel();
        pRemoveHotdog = new removeHotdogItemsPanel();
        pRemoveSandwich = new removeSandwichItemsPanel();
        
        pOrderHistory = new orderHistoryPanel();

        switchPanel.setLayout(layout);

        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;

        switchPanel.add(pAddBurger, c);
        c.gridx = 0;
        c.gridy = 0;
        switchPanel.add(pAddHotdog, c);
        c.gridx = 0;
        c.gridy = 0;
        switchPanel.add(pAddSandwich, c);
        c.gridx = 0;
        c.gridy = 0;

        switchPanel.add(pRemoveBurger, c);
        c.gridx = 0;
        c.gridy = 0;
        switchPanel.add(pRemoveHotdog, c);
        c.gridx = 0;
        c.gridy = 0;
        switchPanel.add(pRemoveSandwich, c);
        c.gridx = 0;
        c.gridy = 0;
        
        switchPanel.add(pOrderHistory, c);
        c.gridx = 0;
        c.gridy = 0;

        pAddBurger.setVisible(false);
        pAddHotdog.setVisible(false);
        pAddSandwich.setVisible(false);

        pRemoveBurger.setVisible(false);
        pRemoveHotdog.setVisible(false);
        pRemoveSandwich.setVisible(false);
        
        pOrderHistory.setVisible(false);

        addBurgerRadioButton.setVisible(false);
        addHotdogRadioButton.setVisible(false);
        addSandwichRadioButton.setVisible(false);

        removeBurgerRadioButton.setVisible(false);
        removeHotdogRadioButton.setVisible(false);
        removeSandwichRadioButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addItemsButtonGroup = new javax.swing.ButtonGroup();
        removeItemsbuttonGroup = new javax.swing.ButtonGroup();
        switchPanel = new javax.swing.JPanel();
        optionPanel = new javax.swing.JPanel();
        addNewItemsButton = new javax.swing.JButton();
        removeItemstButton = new javax.swing.JButton();
        orderHistoryButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addBurgerRadioButton = new javax.swing.JRadioButton();
        addHotdogRadioButton = new javax.swing.JRadioButton();
        addSandwichRadioButton = new javax.swing.JRadioButton();
        removeBurgerRadioButton = new javax.swing.JRadioButton();
        removeHotdogRadioButton = new javax.swing.JRadioButton();
        removeSandwichRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Editor");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        switchPanel.setBackground(new java.awt.Color(204, 204, 204));
        switchPanel.setMaximumSize(new java.awt.Dimension(800, 370));
        switchPanel.setMinimumSize(new java.awt.Dimension(800, 370));
        switchPanel.setPreferredSize(new java.awt.Dimension(800, 370));

        javax.swing.GroupLayout switchPanelLayout = new javax.swing.GroupLayout(switchPanel);
        switchPanel.setLayout(switchPanelLayout);
        switchPanelLayout.setHorizontalGroup(
            switchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        switchPanelLayout.setVerticalGroup(
            switchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        optionPanel.setBackground(new java.awt.Color(102, 0, 0));
        optionPanel.setFocusable(false);
        optionPanel.setMaximumSize(new java.awt.Dimension(800, 130));
        optionPanel.setMinimumSize(new java.awt.Dimension(800, 130));
        optionPanel.setPreferredSize(new java.awt.Dimension(800, 130));

        addNewItemsButton.setBackground(new java.awt.Color(153, 255, 153));
        addNewItemsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addNewItemsButton.setText("Add New Items");
        addNewItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewItemsButtonMouseClicked(evt);
            }
        });

        removeItemstButton.setBackground(new java.awt.Color(255, 255, 153));
        removeItemstButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeItemstButton.setText("Remove Items");
        removeItemstButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeItemstButtonMouseClicked(evt);
            }
        });

        orderHistoryButton.setBackground(new java.awt.Color(255, 153, 255));
        orderHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderHistoryButton.setText("Order History");
        orderHistoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderHistoryButtonMouseClicked(evt);
            }
        });

        addBurgerRadioButton.setBackground(new java.awt.Color(102, 0, 0));
        addItemsButtonGroup.add(addBurgerRadioButton);
        addBurgerRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBurgerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        addBurgerRadioButton.setText("Burger");
        addBurgerRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBurgerRadioButtonMouseClicked(evt);
            }
        });

        addHotdogRadioButton.setBackground(new java.awt.Color(102, 0, 0));
        addItemsButtonGroup.add(addHotdogRadioButton);
        addHotdogRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addHotdogRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        addHotdogRadioButton.setText("Hotdog");
        addHotdogRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addHotdogRadioButtonMouseClicked(evt);
            }
        });

        addSandwichRadioButton.setBackground(new java.awt.Color(102, 0, 0));
        addItemsButtonGroup.add(addSandwichRadioButton);
        addSandwichRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addSandwichRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        addSandwichRadioButton.setText("Sandwich");
        addSandwichRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSandwichRadioButtonMouseClicked(evt);
            }
        });

        removeBurgerRadioButton.setBackground(new java.awt.Color(102, 0, 0));
        removeItemsbuttonGroup.add(removeBurgerRadioButton);
        removeBurgerRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeBurgerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        removeBurgerRadioButton.setText("Burger");
        removeBurgerRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBurgerRadioButtonMouseClicked(evt);
            }
        });

        removeHotdogRadioButton.setBackground(new java.awt.Color(102, 0, 0));
        removeItemsbuttonGroup.add(removeHotdogRadioButton);
        removeHotdogRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeHotdogRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        removeHotdogRadioButton.setText("Hotdog");
        removeHotdogRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeHotdogRadioButtonMouseClicked(evt);
            }
        });

        removeSandwichRadioButton.setBackground(new java.awt.Color(102, 0, 0));
        removeItemsbuttonGroup.add(removeSandwichRadioButton);
        removeSandwichRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeSandwichRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        removeSandwichRadioButton.setText("Sandwich");
        removeSandwichRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeSandwichRadioButtonMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(addNewItemsButton)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(addBurgerRadioButton)
                        .addGap(12, 12, 12)
                        .addComponent(addHotdogRadioButton)
                        .addGap(12, 12, 12)
                        .addComponent(addSandwichRadioButton)))
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(removeBurgerRadioButton)
                        .addGap(12, 12, 12)
                        .addComponent(removeHotdogRadioButton)
                        .addGap(12, 12, 12)
                        .addComponent(removeSandwichRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(removeItemstButton)
                        .addGap(115, 115, 115)
                        .addComponent(orderHistoryButton)))
                .addGap(531, 531, 531))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addNewItemsButton)
                    .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderHistoryButton)
                        .addComponent(removeItemstButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBurgerRadioButton)
                        .addComponent(addHotdogRadioButton)
                        .addComponent(addSandwichRadioButton))
                    .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeBurgerRadioButton)
                            .addComponent(removeHotdogRadioButton)
                            .addComponent(removeSandwichRadioButton))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(switchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(switchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void removeItemstButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeItemstButtonMouseClicked
        addBurgerRadioButton.setVisible(false);
        addHotdogRadioButton.setVisible(false);
        addSandwichRadioButton.setVisible(false);
        removeBurgerRadioButton.setVisible(true);
        removeHotdogRadioButton.setVisible(true);
        removeSandwichRadioButton.setVisible(true);
    }//GEN-LAST:event_removeItemstButtonMouseClicked

    private void addNewItemsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewItemsButtonMouseClicked
        addBurgerRadioButton.setVisible(true);
        addHotdogRadioButton.setVisible(true);
        addSandwichRadioButton.setVisible(true);
        removeBurgerRadioButton.setVisible(false);
        removeHotdogRadioButton.setVisible(false);
        removeSandwichRadioButton.setVisible(false);
    }//GEN-LAST:event_addNewItemsButtonMouseClicked

    private void addBurgerRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBurgerRadioButtonMouseClicked
        pAddBurger.setVisible(true);
        pAddHotdog.setVisible(false);
        pAddSandwich.setVisible(false);
        pRemoveBurger.setVisible(false);
        pRemoveHotdog.setVisible(false);
        pRemoveSandwich.setVisible(false);
        pOrderHistory.setVisible(false);

    }//GEN-LAST:event_addBurgerRadioButtonMouseClicked

    private void removeBurgerRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBurgerRadioButtonMouseClicked
        pAddBurger.setVisible(false);
        pAddHotdog.setVisible(false);
        pAddSandwich.setVisible(false);
        pRemoveBurger.setVisible(true);
        pRemoveHotdog.setVisible(false);
        pRemoveSandwich.setVisible(false);
        pOrderHistory.setVisible(false);
        removeBurgerItemsPanel.removeItems();
        removeBurgerItemsPanel.loadItems();
    }//GEN-LAST:event_removeBurgerRadioButtonMouseClicked

    private void addHotdogRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addHotdogRadioButtonMouseClicked
        pAddBurger.setVisible(false);
        pAddHotdog.setVisible(true);
        pAddSandwich.setVisible(false);
        pRemoveBurger.setVisible(false);
        pRemoveHotdog.setVisible(false);
        pRemoveSandwich.setVisible(false);
        pOrderHistory.setVisible(false);
    }//GEN-LAST:event_addHotdogRadioButtonMouseClicked

    private void addSandwichRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSandwichRadioButtonMouseClicked
        pAddBurger.setVisible(false);
        pAddHotdog.setVisible(false);
        pAddSandwich.setVisible(true);
        pRemoveBurger.setVisible(false);
        pRemoveHotdog.setVisible(false);
        pRemoveSandwich.setVisible(false);
        pOrderHistory.setVisible(false);
    }//GEN-LAST:event_addSandwichRadioButtonMouseClicked

    private void removeHotdogRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeHotdogRadioButtonMouseClicked
        pAddBurger.setVisible(false);
        pAddHotdog.setVisible(false);
        pAddSandwich.setVisible(false);
        pRemoveBurger.setVisible(false);
        pRemoveHotdog.setVisible(true);
        pRemoveSandwich.setVisible(false);
        pOrderHistory.setVisible(false);
        removeHotdogItemsPanel.removeItems();
        removeHotdogItemsPanel.loadItems();
    }//GEN-LAST:event_removeHotdogRadioButtonMouseClicked

    private void removeSandwichRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSandwichRadioButtonMouseClicked
        pAddBurger.setVisible(false);
        pAddHotdog.setVisible(false);
        pAddSandwich.setVisible(false);
        pRemoveBurger.setVisible(false);
        pRemoveHotdog.setVisible(false);
        pRemoveSandwich.setVisible(true);
        pOrderHistory.setVisible(false);
        removeSandwichItemsPanel.removeItems();
        removeSandwichItemsPanel.loadItems();
    }//GEN-LAST:event_removeSandwichRadioButtonMouseClicked

    private void orderHistoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderHistoryButtonMouseClicked
        addBurgerRadioButton.setVisible(false);
        addHotdogRadioButton.setVisible(false);
        addSandwichRadioButton.setVisible(false);
        removeBurgerRadioButton.setVisible(false);
        removeHotdogRadioButton.setVisible(false);
        removeSandwichRadioButton.setVisible(false);
        pAddBurger.setVisible(false);
        pAddHotdog.setVisible(false);
        pAddSandwich.setVisible(false);
        pRemoveBurger.setVisible(false);
        pRemoveHotdog.setVisible(false);
        pRemoveSandwich.setVisible(false);
        pOrderHistory.setVisible(true);
    }//GEN-LAST:event_orderHistoryButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminEditingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminEditingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminEditingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminEditingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addBurgerRadioButton;
    private javax.swing.JRadioButton addHotdogRadioButton;
    private javax.swing.ButtonGroup addItemsButtonGroup;
    private javax.swing.JButton addNewItemsButton;
    private javax.swing.JRadioButton addSandwichRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel optionPanel;
    private javax.swing.JButton orderHistoryButton;
    private javax.swing.JRadioButton removeBurgerRadioButton;
    private javax.swing.JRadioButton removeHotdogRadioButton;
    private javax.swing.ButtonGroup removeItemsbuttonGroup;
    private javax.swing.JButton removeItemstButton;
    private javax.swing.JRadioButton removeSandwichRadioButton;
    private javax.swing.JPanel switchPanel;
    // End of variables declaration//GEN-END:variables
}
