/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Krish
 */
public class removeSandwichItemsPanel extends javax.swing.JPanel {

    /**
     * Creates new form removeSandwichPanel
     */
    public removeSandwichItemsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sandwichPicLLabel = new javax.swing.JLabel();
        removeSandwichItemsLabel = new javax.swing.JLabel();
        sandwichPicRLabel = new javax.swing.JLabel();
        sandwichIng1Label = new javax.swing.JLabel();
        sIng1Box = new javax.swing.JComboBox<>();
        sandwichIng2Label = new javax.swing.JLabel();
        sIng2Box = new javax.swing.JComboBox<>();
        sandwichIng3Label = new javax.swing.JLabel();
        sIng3Box = new javax.swing.JComboBox<>();
        sandwichIng4Label = new javax.swing.JLabel();
        sIng4Box = new javax.swing.JComboBox<>();
        sideLabel = new javax.swing.JLabel();
        sideBox = new javax.swing.JComboBox<>();
        drinkLabel = new javax.swing.JLabel();
        drinkBox = new javax.swing.JComboBox<>();
        saveRemoveSandwichItemsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));
        setMaximumSize(new java.awt.Dimension(800, 370));
        setMinimumSize(new java.awt.Dimension(800, 370));

        sandwichPicLLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/Real Sprites/SandwichButton_BW.png"))); // NOI18N

        removeSandwichItemsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        removeSandwichItemsLabel.setText("Remove Sandwich Items");

        sandwichPicRLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/Real Sprites/SandwichButton_BW.png"))); // NOI18N

        sandwichIng1Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sandwichIng1Label.setText("Ingredient 1:");

        sIng1Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        sandwichIng2Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sandwichIng2Label.setText("Ingredient 2:");

        sIng2Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        sandwichIng3Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sandwichIng3Label.setText("Ingredient 3:");

        sIng3Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        sandwichIng4Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sandwichIng4Label.setText("Ingredient 4:");

        sIng4Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        sideLabel.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sideLabel.setText("Side:");

        sideBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        drinkLabel.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        drinkLabel.setText("Drink:");

        drinkBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        saveRemoveSandwichItemsButton.setBackground(new java.awt.Color(204, 255, 255));
        saveRemoveSandwichItemsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveRemoveSandwichItemsButton.setText("Remove Selected Items");
        saveRemoveSandwichItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveRemoveSandwichItemsButtonMouseClicked(evt);
            }
        });
        saveRemoveSandwichItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRemoveSandwichItemsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sandwichPicLLabel)
                        .addGap(35, 35, 35)
                        .addComponent(removeSandwichItemsLabel)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sandwichIng1Label)
                            .addComponent(sandwichIng2Label)
                            .addComponent(sandwichIng3Label)
                            .addComponent(sandwichIng4Label))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sIng4Box, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sIng3Box, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sIng2Box, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sIng1Box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sideBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(drinkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sideLabel)
                            .addComponent(drinkLabel)
                            .addComponent(saveRemoveSandwichItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sandwichPicRLabel))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(removeSandwichItemsLabel))
                    .addComponent(sandwichPicRLabel)
                    .addComponent(sandwichPicLLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sIng1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sandwichIng1Label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sIng2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sandwichIng2Label))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sIng3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sandwichIng3Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sideBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sideLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drinkBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkLabel))))
                .addGap(9, 9, 9)
                .addComponent(saveRemoveSandwichItemsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sIng4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sandwichIng4Label))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveRemoveSandwichItemsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveRemoveSandwichItemsButtonMouseClicked
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to remove the selected item(s)?", "Save Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        }
        // <editor-fold>//saveIngredients
        if (!sIng1Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.singredients1.size(); i++) {
                if (FinalProject.singredients1.get(i).equals(sIng1Box.getSelectedItem().toString())) {
                    FinalProject.singredients1.remove(i);
                    break;
                }
            }
            addSandwichItemsPanel.saveSIng1();
        }
        if (!sIng2Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.singredients2.size(); i++) {
                if (FinalProject.singredients2.get(i).equals(sIng2Box.getSelectedItem().toString())) {
                    FinalProject.singredients2.remove(i);
                    break;
                }
            }
            addSandwichItemsPanel.saveSIng2();
        }
        if (!sIng3Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.singredients3.size(); i++) {
                if (FinalProject.singredients3.get(i).equals(sIng3Box.getSelectedItem().toString())) {
                    FinalProject.singredients3.remove(i);
                    break;
                }
            }
            addSandwichItemsPanel.saveSIng3();
        }
        if (!sIng4Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.singredients4.size(); i++) {
                if (FinalProject.singredients4.get(i).equals(sIng4Box.getSelectedItem().toString())) {
                    FinalProject.singredients4.remove(i);
                    break;
                }
            }
            addSandwichItemsPanel.saveSIng4();
        }
        if (!sideBox.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.sideOrder.size(); i++) {
                if (FinalProject.sideOrder.get(i).equals(sideBox.getSelectedItem().toString())) {
                    FinalProject.sideOrder.remove(i);
                    break;
                }
            }
            addSandwichItemsPanel.saveSide();
        }
        if (!drinkBox.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.drinkOrder.size(); i++) {
                if (FinalProject.drinkOrder.get(i).equals(drinkBox.getSelectedItem().toString())) {
                    FinalProject.drinkOrder.remove(i);
                    break;
                }
            }
            addSandwichItemsPanel.saveDrink();
        }
        removeItems();
        loadItems();
        // </editor-fold>//ingredient arrays
    }//GEN-LAST:event_saveRemoveSandwichItemsButtonMouseClicked

    private void saveRemoveSandwichItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRemoveSandwichItemsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveRemoveSandwichItemsButtonActionPerformed

    public static void removeItems() {
        sIng1Box.removeAllItems();
        sIng2Box.removeAllItems();
        sIng3Box.removeAllItems();
        sIng4Box.removeAllItems();
        sideBox.removeAllItems();
        drinkBox.removeAllItems();
    }

    public static void loadItems() {
        // <editor-fold>//load Items       
        sIng1Box.addItem("N/A");
        sIng2Box.addItem("N/A");
        sIng3Box.addItem("N/A");
        sIng4Box.addItem("N/A");
        sideBox.addItem("N/A");
        drinkBox.addItem("N/A");
        for (int i = 0; i < FinalProject.singredients1.size(); i++) {
            sIng1Box.addItem(FinalProject.singredients1.get(i));
        }
        for (int i = 0; i < FinalProject.singredients2.size(); i++) {
            sIng2Box.addItem(FinalProject.singredients2.get(i));
        }
        for (int i = 0; i < FinalProject.singredients3.size(); i++) {
            sIng3Box.addItem(FinalProject.singredients3.get(i));
        }
        for (int i = 0; i < FinalProject.singredients4.size(); i++) {
            sIng4Box.addItem(FinalProject.singredients4.get(i));
        }
        for (int i = 0; i < FinalProject.sideOrder.size(); i++) {
            sideBox.addItem(FinalProject.sideOrder.get(i));
        }
        for (int i = 0; i < FinalProject.drinkOrder.size(); i++) {
            drinkBox.addItem(FinalProject.drinkOrder.get(i));
        }
        // </editor-fold>//end load Items
    }

    private JFrame frame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> drinkBox;
    private javax.swing.JLabel drinkLabel;
    private javax.swing.JLabel removeSandwichItemsLabel;
    private static javax.swing.JComboBox<String> sIng1Box;
    private static javax.swing.JComboBox<String> sIng2Box;
    private static javax.swing.JComboBox<String> sIng3Box;
    private static javax.swing.JComboBox<String> sIng4Box;
    private javax.swing.JLabel sandwichIng1Label;
    private javax.swing.JLabel sandwichIng2Label;
    private javax.swing.JLabel sandwichIng3Label;
    private javax.swing.JLabel sandwichIng4Label;
    private javax.swing.JLabel sandwichPicLLabel;
    private javax.swing.JLabel sandwichPicRLabel;
    private javax.swing.JButton saveRemoveSandwichItemsButton;
    private static javax.swing.JComboBox<String> sideBox;
    private javax.swing.JLabel sideLabel;
    // End of variables declaration//GEN-END:variables
}
