/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Krish
 */
public class removeBurgerItemsPanel extends javax.swing.JPanel {

    public removeBurgerItemsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        burgerPicLLabel = new javax.swing.JLabel();
        removeBurgerItemsLabel = new javax.swing.JLabel();
        burgerPicRLabel = new javax.swing.JLabel();
        burgerIng1Label = new javax.swing.JLabel();
        burgerIng2Label = new javax.swing.JLabel();
        burgerIng3Label = new javax.swing.JLabel();
        burgerIng4Label = new javax.swing.JLabel();
        sideLabel = new javax.swing.JLabel();
        drinkLabel = new javax.swing.JLabel();
        bIng1Box = new javax.swing.JComboBox<>();
        bIng2Box = new javax.swing.JComboBox<>();
        bIng3Box = new javax.swing.JComboBox<>();
        bIng4Box = new javax.swing.JComboBox<>();
        sideBox = new javax.swing.JComboBox<>();
        drinkBox = new javax.swing.JComboBox<>();
        saveRemoveBurgerItemsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));
        setMaximumSize(new java.awt.Dimension(800, 370));
        setMinimumSize(new java.awt.Dimension(800, 370));

        burgerPicLLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/Real Sprites/BugerButton_BW.png"))); // NOI18N

        removeBurgerItemsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        removeBurgerItemsLabel.setText("Remove Burger Items");

        burgerPicRLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/Real Sprites/BugerButton_BW.png"))); // NOI18N

        burgerIng1Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng1Label.setText("Ingredient 1:");

        burgerIng2Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng2Label.setText("Ingredient 2:");

        burgerIng3Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng3Label.setText("Ingredient 3:");

        burgerIng4Label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        burgerIng4Label.setText("Ingredient 4:");

        sideLabel.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sideLabel.setText("Side:");

        drinkLabel.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        drinkLabel.setText("Drink:");

        bIng1Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bIng2Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bIng3Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bIng4Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        sideBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        drinkBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        saveRemoveBurgerItemsButton.setBackground(new java.awt.Color(204, 255, 255));
        saveRemoveBurgerItemsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveRemoveBurgerItemsButton.setText("Remove Selected Items");
        saveRemoveBurgerItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveRemoveBurgerItemsButtonMouseClicked(evt);
            }
        });
        saveRemoveBurgerItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRemoveBurgerItemsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(burgerPicLLabel)
                        .addGap(35, 35, 35)
                        .addComponent(removeBurgerItemsLabel)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(burgerIng1Label)
                            .addComponent(burgerIng2Label)
                            .addComponent(burgerIng3Label)
                            .addComponent(burgerIng4Label))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bIng4Box, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIng3Box, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIng2Box, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIng1Box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sideBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(drinkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sideLabel)
                            .addComponent(drinkLabel)
                            .addComponent(saveRemoveBurgerItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(burgerPicRLabel))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(removeBurgerItemsLabel))
                    .addComponent(burgerPicRLabel)
                    .addComponent(burgerPicLLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIng1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(burgerIng1Label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bIng2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burgerIng2Label))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bIng3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burgerIng3Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sideBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sideLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drinkBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkLabel))))
                .addGap(9, 9, 9)
                .addComponent(saveRemoveBurgerItemsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIng4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(burgerIng4Label))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveRemoveBurgerItemsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveRemoveBurgerItemsButtonMouseClicked
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to remove the selected item(s)?", "Save Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        }
        // <editor-fold>//saveIngredients
        if (!bIng1Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.bingredients1.size(); i++) {
                if (FinalProject.bingredients1.get(i).equals(bIng1Box.getSelectedItem().toString())) {
                    FinalProject.bingredients1.remove(i);
                    break;
                }
            }
            addBurgerItemsPanel.saveBIng1();
        }
        if (!bIng2Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.bingredients2.size(); i++) {
                if (FinalProject.bingredients2.get(i).equals(bIng2Box.getSelectedItem().toString())) {
                    FinalProject.bingredients2.remove(i);
                    break;
                }
            }
            addBurgerItemsPanel.saveBIng2();
        }
        if (!bIng3Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.bingredients3.size(); i++) {
                if (FinalProject.bingredients3.get(i).equals(bIng3Box.getSelectedItem().toString())) {
                    FinalProject.bingredients3.remove(i);
                    break;
                }
            }
            addBurgerItemsPanel.saveBIng3();
        }
        if (!bIng4Box.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.bingredients4.size(); i++) {
                if (FinalProject.bingredients4.get(i).equals(bIng4Box.getSelectedItem().toString())) {
                    FinalProject.bingredients4.remove(i);
                    break;
                }
            }
            addBurgerItemsPanel.saveBIng4();
        }
        if (!sideBox.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.sideOrder.size(); i++) {
                if (FinalProject.sideOrder.get(i).equals(sideBox.getSelectedItem().toString())) {
                    FinalProject.sideOrder.remove(i);
                    break;
                }
            }
            addBurgerItemsPanel.saveSide();
        }
        if (!drinkBox.getSelectedItem().toString().equals("N/A")) {
            for (int i = 0; i < FinalProject.drinkOrder.size(); i++) {
                if (FinalProject.drinkOrder.get(i).equals(drinkBox.getSelectedItem().toString())) {
                    FinalProject.drinkOrder.remove(i);
                    break;
                }
            }
            addBurgerItemsPanel.saveDrink();
        }
        removeItems();
        loadItems();
        // </editor-fold>//ingredient arrays
    }//GEN-LAST:event_saveRemoveBurgerItemsButtonMouseClicked

    private void saveRemoveBurgerItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRemoveBurgerItemsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveRemoveBurgerItemsButtonActionPerformed

    public static void removeItems() {
        bIng1Box.removeAllItems();
        bIng2Box.removeAllItems();
        bIng3Box.removeAllItems();
        bIng4Box.removeAllItems();
        sideBox.removeAllItems();
        drinkBox.removeAllItems();
    }

    public static void loadItems() {
        // <editor-fold>//load Items       
        bIng1Box.addItem("N/A");
        bIng2Box.addItem("N/A");
        bIng3Box.addItem("N/A");
        bIng4Box.addItem("N/A");
        sideBox.addItem("N/A");
        drinkBox.addItem("N/A");
        for (int i = 0; i < FinalProject.bingredients1.size(); i++) {
            bIng1Box.addItem(FinalProject.bingredients1.get(i));
        }
        for (int i = 0; i < FinalProject.bingredients2.size(); i++) {
            bIng2Box.addItem(FinalProject.bingredients2.get(i));
        }
        for (int i = 0; i < FinalProject.bingredients3.size(); i++) {
            bIng3Box.addItem(FinalProject.bingredients3.get(i));
        }
        for (int i = 0; i < FinalProject.bingredients4.size(); i++) {
            bIng4Box.addItem(FinalProject.bingredients4.get(i));
        }
        for (int i = 0; i < FinalProject.sideOrder.size(); i++) {
            sideBox.addItem(FinalProject.sideOrder.get(i));
        }
        for (int i = 0; i < FinalProject.drinkOrder.size(); i++) {
            drinkBox.addItem(FinalProject.drinkOrder.get(i));
        }
        // </editor-fold>//end load Items
    }

    private JFrame frame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> bIng1Box;
    private static javax.swing.JComboBox<String> bIng2Box;
    private static javax.swing.JComboBox<String> bIng3Box;
    private static javax.swing.JComboBox<String> bIng4Box;
    private javax.swing.JLabel burgerIng1Label;
    private javax.swing.JLabel burgerIng2Label;
    private javax.swing.JLabel burgerIng3Label;
    private javax.swing.JLabel burgerIng4Label;
    private javax.swing.JLabel burgerPicLLabel;
    private javax.swing.JLabel burgerPicRLabel;
    private static javax.swing.JComboBox<String> drinkBox;
    private javax.swing.JLabel drinkLabel;
    private javax.swing.JLabel removeBurgerItemsLabel;
    private javax.swing.JButton saveRemoveBurgerItemsButton;
    private static javax.swing.JComboBox<String> sideBox;
    private javax.swing.JLabel sideLabel;
    // End of variables declaration//GEN-END:variables
}
